version: "3"

services:
  mongodb.local:
    image: mongo
    restart: always
    container_name: mongodb.local
    environment:
      VIRTUAL_HOST: mongodb.local


networks:
  default:
    external:
      name: nginx-proxy
