version: "3"

services:
  mysql.local:
    image: mysql:5.6
    restart: always
    container_name: mysql.local
    volumes:
      - ./data:/var/lib/mysql
    environment:
      VIRTUAL_HOST: mysql.local
      MYSQL_ROOT_PASSWORD: root

networks:
  default:
    external:
      name: nginx-proxy
